project:
  type: website

website:
  title: "Raquel Luna"
  navbar:
    background: info
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Assignments"
        menu:
          - href: sub1.qmd
            text: "Assignment 1"
          - href: sub2.qmd
            text: "Assignment 2"
          - href: sub3.qmd
            text: "Assignment 3"
          - href: sub4.qmd
            text: "Assignment 4"
          - href: sub5.qmd
            text: "Assignment 5"

      - text: "Reviews"
        menu: 
          - href: rev1.qmd
            text: "Edward Tufte (2016) The Future of Data Analysis Review"
            
      - text: "Final Projects"
        menu:
          - href: files/EPPS%206356%20Final%20Project.pdf
            text: "EPPS 6356 Final (PDF)"
        
    right: 
      - icon: github
        href: https://raqueluna96.github.io/Raquel1/
  sidebar: 
    style: "docked"
    search: true

format:
  html:
    grid: 
      sidebar-width: 300px
      body-width: 650px
      margin-width: 450px
    theme: minty
    css: custom.css
    toc: true

editor: visual

