---
title: "Edward Tufte's *The Future of Data Analysis* Review" 
author: Raquel Luna
editor: visual
format:
  html:
    page-layout: article
    progress: true
    scrollable: true
---

## Review and Reflection on the Video: "The Future of Data Analysis" by Dr. Edward Tufte

In the keynote session of the Microsoft Machine Learning & Data Science Summit 2016, Dr. Edward Tufte presented on *“The Future of Data Analysis.”* Dr. Tufte emphasized that data analysis is about “turning information into conclusions,” while analytical thinking involves “assessing and evaluating the relationship between information and conclusions.” The goal of data visualization, according to him, is to “assist reasoning about its content.” This suggests that data visualization should help in illustrating the connections between “information and conclusions,” such as demonstrating causal mechanisms or models that aim to describe, explain, and predict observed phenomena.

One of the more alarming points Tufte raised was the current crisis in data analysis, highlighting that many published studies are often incorrect. He referred to an article by *John P. A. Ioannidis*, which claims that over 35 percent of published research findings are false due to factors like study power and bias. Tufte also cited *Lazer and colleagues' (2014)* work on the 'Google Flu' case to illustrate the dangers of overfitting in big data analysis. Even more concerning is that not only are the original studies’ findings and conclusions often not replicable, but replication studies also fail to achieve consistent results. This calls into question the overall validity of data analyses in empirical research.

Tufte’s assertion that “human science is not rocket science; it is harder than rocket science” is particularly striking. Human behavior and societal dynamics are incredibly complex and ever-changing. This makes data analysis in the social sciences a challenging and evolving field that requires constant refinement and development. So, what is the future of data analysis? According to Tufte, it lies in making a clear distinction between studies that are confirmatory and free from manipulation, and those that are exploratory in nature. He emphasizes that findings should not be manufactured from the data itself but should arise from rigorous and unbiased analysis. Ensuring the quality of data analysis in the social sciences requires us to remain vigilant, judicious, and adaptable. This approach will enable us to generate data analyses and conclusions that are as accurate and reliable as possible.